### ISSUE TITLE
Add a makefile

### ISSUE THREAD

**Issue by 414owen** [sidroopdaska/todo-ts-aspnetmvc-starter#1]
Please

**Comment by m1cr0man** [comment]
I added a Makefile, but there is a problem. When you use `docker-run` to start the container, it cannot be killed with Ctrl+C. The signal seems to kill Make, which in turn does not pass the signal to docker run. It causes a deadlock and make starts consuming a CPU core.

If we could change the kill command for the webapp to something other than Ctrl+C that would be great, although I can't see any way to do so.
